# Generated by Django 3.2.8 on 2021-10-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru', models.CharField(db_index=True, default='', max_length=1000, verbose_name='На русском')),
                ('kk', models.CharField(blank=True, db_index=True, default='', max_length=1000, verbose_name='На казахском')),
                ('en', models.CharField(blank=True, db_index=True, default='', max_length=1000, verbose_name='На английском')),
            ],
            options={
                'verbose_name': 'Поле с переводом',
                'verbose_name_plural': 'Поля с переводом',
            },
        ),
    ]
