# Generated by Django 3.2.8 on 2021-10-28 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('additional_fields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Код для внутреннего использования')),
                ('is_default', models.BooleanField(default=False, verbose_name='Значение по умолчанию')),
                ('sort_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядковое значение для сортировки')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='additional_fields.translationfield', verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
    ]
