# Generated by Django 3.2.8 on 2021-10-28 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20211028_1811'),
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='coordinates',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='coordinatess', to='weather.coordinates', verbose_name='Координаты'),
        ),
    ]
