# Generated by Django 3.2.8 on 2021-10-28 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('additional_fields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('is_deleted', models.BooleanField(default=False, null=True, verbose_name='Удалено')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='additional_fields.translationfield', verbose_name='Наименование')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signup_user', to=settings.AUTH_USER_MODEL, verbose_name='Основной пользователь')),
            ],
            options={
                'verbose_name': 'Погода',
                'verbose_name_plural': 'Погоды',
            },
        ),
    ]
