# Generated by Django 3.2.8 on 2021-10-28 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
            ],
        ),
        migrations.RemoveField(
            model_name='weather',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='longitude',
        ),
        migrations.AddField(
            model_name='weather',
            name='coordinates',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='coordinates', to='weather.coordinates', verbose_name='Координаты'),
        ),
    ]
