# Generated by Django 3.2.8 on 2021-11-06 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20211028_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('source', models.CharField(blank=True, choices=[('OPEN_WEATHER', 'Open Weather data'), ('OPEN_WEATHER_PREMIUM', 'PREMIUM Open Weather data')], default='OPEN_WEATHER', max_length=30, null=True, verbose_name='Вид погодных данных')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Данные о погоде')),
                ('weather', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='weathers', to='weather.weather', verbose_name='ID погоды')),
            ],
            options={
                'verbose_name': 'OpenWeather',
                'verbose_name_plural': 'OpenWeathers',
            },
        ),
    ]
